package com.example.parkingapi.service.mpesa

import com.google.gson.annotations.SerializedName

data class C2BPaymentRequest(
    @SerializedName("input_Amount") val amount: String,
    @SerializedName("input_CustomerMSISDN") val customerMSISDN: String,
    @SerializedName("input_ThirdPartyReference") val thirdPartyReference: String,
    @SerializedName("input_ServiceProviderCode") val serviceProviderCode: String,
    @SerializedName("input_TransactionReference") val transactionReference: String,
)

/**
 * Data class that represents the response from the Customer-to-Business (C2B) Mpesa Transaction
 * @output_ConversationID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform.
 * @output_ResponseCode: This gets generated by the iPG platform to indicate the status of the transaction
 * @output_TransactionID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform.
 * @output_ResponseDesc: This gets generated by the iPG platform to indicate the status of the transaction
 */
data class PaymentResponse(
    @SerializedName("output_ResponseCode") val responseCode: String = "",
    @SerializedName("output_ResponseDesc") val responseDesc: String = "",
    @SerializedName("output_TransactionID") val transactionId: String? = null,
    @SerializedName("output_ConversationID") val conversationId: String? = null,
    @SerializedName("output_ThirdPartyReference") val reference: String? = null,
)